# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b71f91ec65c9750cdce8860eef632ee2fafc8d3d01989e6c46428f61bf343ef34e7a5b436c466587888fca0d0fc63299923e84173d9cd81dd68de51a2a39d9

test:
  secret_key_base: b642ffa02567c9acd1aa9dbf3de61ee27541596195836ebc705d29bde6160fc123954462f5969ef7c5812f5bd32052a43129dec1467d4ac3fc134c916436f2a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
